// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFuEyiJ7QS5f4hYq0qXZOSQ4bm6TbkVY',
    appId: '1:122925758220:web:60aaf0f5d61d1771e7fb29',
    messagingSenderId: '122925758220',
    projectId: 'strife-aeeb5',
    authDomain: 'strife-aeeb5.firebaseapp.com',
    storageBucket: 'strife-aeeb5.firebasestorage.app',
    measurementId: 'G-EZD0KTDS5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBAll9ukq_bZbzQdxpKVt2-_6ojb9ttw',
    appId: '1:122925758220:android:d2f76750d15d508fe7fb29',
    messagingSenderId: '122925758220',
    projectId: 'strife-aeeb5',
    storageBucket: 'strife-aeeb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjtxKBhlotgwyZePCz2Xd_LdqJz4rS7o',
    appId: '1:122925758220:ios:cfd5ea13d4e929f1e7fb29',
    messagingSenderId: '122925758220',
    projectId: 'strife-aeeb5',
    storageBucket: 'strife-aeeb5.firebasestorage.app',
    iosBundleId: 'com.example.strife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUjtxKBhlotgwyZePCz2Xd_LdqJz4rS7o',
    appId: '1:122925758220:ios:cfd5ea13d4e929f1e7fb29',
    messagingSenderId: '122925758220',
    projectId: 'strife-aeeb5',
    storageBucket: 'strife-aeeb5.firebasestorage.app',
    iosBundleId: 'com.example.strife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiFuEyiJ7QS5f4hYq0qXZOSQ4bm6TbkVY',
    appId: '1:122925758220:web:39ca30e8f87851d9e7fb29',
    messagingSenderId: '122925758220',
    projectId: 'strife-aeeb5',
    authDomain: 'strife-aeeb5.firebaseapp.com',
    storageBucket: 'strife-aeeb5.firebasestorage.app',
    measurementId: 'G-05SVFMS0P4',
  );

}